### ISSUE TITLE
Organizing components in the right folders

### ISSUE THREAD

**Issue by kyl00h** [fitstic-project-work-2024/martinator-frontend-old#46]
Some components are only used once and they should be put in the pages folder, while the ones that are repeated should stay in the components folder (like Searchbox.tsx).

Example:
VideocameraCard.tsx will only be used once, it should be put inside pages/Home/ , in the Home folder there will be Home.tsx and VideocameraCard.tsx

Other pages such as Login, Register should also be put inside a corresponding folder.

@uomoazione

**Comment by uomoazione** [comment]
Correct Mister Aboom @kyl00h , I'm on it.
